#!/bin/sh
set -x
MASK_JOBS="sys-fs-fuse-connections.mount systemd-initctl.socket getty.target"
systemctl mask ${MASK_JOBS}
for i in ${MASK_JOBS};do find /usr/lib/systemd/ -iname $i | grep ".wants" | xargs rm -f; done
#chmod 6550 /usr/lib/systemd/systemd 
#${APP_ROOT}/bin/systemd_entrypoint
#ln -fs ${APP_ROOT}/bin/systemd_entrypoint /sbin/init
